version: 2
jobs:
  build:
    working_directory: /go/src/github.com/alexbrand/dockerception
    docker:
      - image: docker:stable-dind
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ./test.sh
      - run: echo "$CIRCLE_TAG"
      - run: env | grep CIRCLE | grep -v "TOKEN"

deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
