version: 2
jobs:
  build:
    working_directory: /go/src/github.com/alexbrand/dockerception
    docker:
      - image: docker:stable-dind
    steps:
      - run: echo "$CIRCLE_TAG"
      - run: env | grep CIRCLE | grep -v "TOKEN"
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - build

deployment:
  fake_deploy:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
