version: 2
jobs:
  build:
    working_directory: /go/src/github.com/alexbrand/dockerception
    docker:
      - image: docker:stable-dind
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ./test.sh
